---
title: "Análisis Exploratorio de las mejores 1000 películas/series según IMBD"
format: html
editor: visual
theme: darkly
toc: true
---

## Introducción

En este proyecto se analizarán las mejores 1000 películas/series según IMBD, donde algunas variables de interés serán los actores, el género de la película/serie, ganancia de la película/serie, año de lanzamiento, número de votos, calificación, entre otros.

IMBD corresponde a una página web principalmente de películas y series, donde la principal característica de esta es poder ver la calificación de una película o serie, donde tanto los críticos profesionales como cualquier persona le pueden dar una nota del 1 al 10 para luego obtener el promedio de las calificaciones. También existen otros apartados como poder ver la trama, el elenco, reseñas de los usuarios y críticos, el equipo de producción y entre otras cosas mas de la película o serie en cuestión que se consulte.

El análisis tiene como enfoque resolver principalmente las siguientes preguntas:

-   ¿Qué género es mas popular en términos de ganancias?

-   ¿Existe alguna relación entre la ganancia y la calificación?

-   ¿Son las películas/series mas antiguas las que tienen mejor calificación?

-   Las películas/series con mejor calificación ¿tienen en general menor número de votos?

Las preguntas anteriores tienen el objetivo principal de darnos a entender de mejor forma que cosas nosotros como espectadores valoramos más en las películas/series que vemos, lo cual puede llevarnos a comprender cómo los creadores de las películas y series se aprovechan de esto para obtener mejores calificaciones y/o ganancias.

Se comenzará con una descripción de las variables a utilizar en el proyecto para ya luego ir resolviendo las preguntas establecidas a través del análisis de gráficos y variables, y así presentar los resultados y conclusiones obtenidas correspondientes. Se finalizará con una conclusión, donde se discutirá como los creadores de películas/series pueden aprovecharse del comportamiento de los espectadores para obtener mejores resultados en términos de calificaciones y/o ganancias.
